### ISSUE TITLE
Masternode Expiring

### ISSUE THREAD

**Issue by oriz456** [Divicoin/Divi#82] opened 2018-08-18 17:12 UTC
In addition to the issues experienced in Issue #81 Another issue I've encountered is the masternode just randomly stopped working. I was by my computer the whole time so there was no connection issue and nothing was closed. After a while, listmasternodes even from local returned a list of masternodes that did not include mine. However, rewards were still coming in(unless they were staking rewards but I don't believe it's possible to stake while the coins are allocated and funding the masternode) which means the masternode may have still been live just not listing itself. getstakingstatus returned everything true. Upon using startmasternode the masternode was showing on the list again. Interestingly, while the balance was still going up since rewards were coming in, in addition to not showing on listmasternodes,  listunspent was also not updating(checking it each time kept returning the same number of transactions). Getinfo returned similar results(except for timeoffset and connections) in both. 

![7c9c2916e5a2b56ce4ee4fabb19cf897696b06b1](https://user-images.githubusercontent.com/32154971/44301549-d4225e00-a2e6-11e8-863d-03c712dbbd46.png)

After running startmasternode, the masternode showed up in listmasternodes again, and listunspent was updating. However all other issues from #81 are still happening, and I have to restart the masternode pretty frequently.

**Comment by oriz456** [comment] 2018-08-18 23:25
I should note this happens with Windows.

**Comment by oriz456** [comment] 2018-08-20 17:17
So an update to this issue: per issue #81, listmasternodes does not return consistent results. I have found(and so have a few other testers) that you can call it one time and you will receive a list of all the masternodes, but other times it will be a partial list, or some other times some will come back as EXPIRED. This seems to happen shortly beore they don't show up at all. Here is an example with one of mine:

“rank” : 0,
“network” : “ipv4”,
“txhash” : “e2e38c3d19923ae01cfe30c1c04ccc7a8df37ae74025981c765c0f89d2f059fa”,
“outidx” : 1,
“status” : “EXPIRED”,
“addr” : “DNaapfjsGgx8RyKpgjxJKvhcQtvST7S7cu”,
“version” : 70913,
“lastseen” : 1534631947,
“activetime” : 0,
“lastpaid” : 0,
“tier” : “COPPER”

Shortly after I called this, it stopped showing up at all. To make matters even more complicated, at times it will continue receiving rewards even though it is not visible, but other times it seems to completely stop.

The experiment I just detailed in my comment to issue #81 seemed to have worked for a little bit and kept it live for longer than 2 hours which was the average time before, but still disappeared eventually, although kept receiving rewards that way. After changing the divi.conf files back to normal, I now have 2 masternodes that are not showing but are still receiving rewards, and 2 that are not showing and not receiving rewards.Also, sometimes "Expired" ones will come back online on their own(as in, calling listmasternodes will already show them again without doing anything), but sometimes they won't. 

Update: listmasternodes this morning only listed one of my masternode along with 3 others; now, it just lists one total which isn’t mine(I believe it’s Giff’s diamond). I checked this morning(4 hours ago) my listaddressgroupings, to see who keeps receiving rewards. Interestingly, my diamond is, and so is my one copper(my diamond was the only one still appearing for a while but that copper wasn’t, regardless, even now they both keep receiving rewards). On the other hand the other two seem to truly have stopped, because they have been receiving nothing so far. I’ll keep checking the balance in each account for a few more hours before I start them again, but they are all configured precisely the same way. Another curiosity is that even though last night I finished my experiment and changed the divi.conf files back to being the way they should, my diamond server can still listmasternodes, but my other remote servers can’t. I have done this all with using the “add” command for addnode instead of onetry. I will next be trying to take only certain lines out of the “long” divi.conf and experimenting with each individual one in the local divi.conf.

**Comment by 99darwin** [comment] 2018-08-20 19:34
#123 in vso

**Comment by Divicoin** [comment] 2018-08-22 02:14
Onetry establishes direct connection, without adding to cache. 

Closing as not a bug.

**Comment by oriz456** [comment] 2018-08-24 00:35
Masternode seems stable, if keeps running for another day, can probably close issue. However, the real issue is _still_ listmasternodes. It initially seemed like this was better, but it is still very inconsistent and will give different results on different servers. Right now I'm only showing one masternode online, even though all 5 of mine are running based on getmasternodestatus and the fact they're receiving rewards.

**Closed** 2018-08-30 00:29 UTC
