### ISSUE TITLE
Multiple unlock timers allowed at once

### ISSUE THREAD

**Issue by justinpatten** [Divicoin/Divi#66] opened 2018-07-17 20:19 UTC
# Expected behavior
Only one active timer should be allowed for the wallet unlock
When unlocked successfully, unlock modal should go away

# Actual behavior
Multiple timers can be active
User must manually close the unlock window

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [x] Windows 10

# Steps to reproduce the problem
1 - Open the UI
2 - Go to settings
3 - Unlock your wallet (Note - pop up should close when you press unlock, if successful)
4 - Unlock your wallet again before the timer elapses
5 - Watch the countdown jump between the time remaining of the two timers

**Comment by Divicoin** [comment] 2018-07-20 01:02
Known issue. Potential duplicate of https://github.com/Divicoin/Divi/issues/58

**Comment by 99darwin** [comment] 2018-08-09 15:48
Staged for testing

**Comment by Divicoin** [comment] 2018-08-14 21:25
Closed in 1.1.26

**Closed by Divicoin** 2018-08-14 21:25 UTC
Labels: GUI, duplicate
