### ISSUE TITLE
Fees shown to 0 but 0.0000225 is taken

### ISSUE THREAD

**Issue by oriz456** [Divicoin/Divi#62] opened 2018-07-14 00:39 UTC
# Expected behavior
When sending coins the correct fee with the correct decimals should be shown
# Actual behavior
Gives a round 0 for fee with no decimals even though 0.0000225 is taken which is only shown afterwards in history. I opened a new one even though one for MAC already exists since this is on windows.
# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [x] Windows 10

# Steps to reproduce the problem
Simply try to send 1 divi to an address and then check the history and compare it to the confirm message prior to sending the funds.

**Comment by Divicoin** [comment] 2018-07-20 01:03
Is this through the CLI or GUI client?

**Comment by Divicoin** [comment] 2018-07-20 01:09
Looks to be a duplicate of https://github.com/Divicoin/Divi/issues/36. Closing for consolidation.

**Closed by Divicoin** 2018-07-20 01:09 UTC
