### ISSUE TITLE
addnode 178.62.195.16 onetry does not add the node

### ISSUE THREAD

**Issue by oriz456** [Divicoin/Divi#83] opened 2018-08-20 17:16 UTC
See below, attempting to remove it right after giving it the command returns a result that it was never added. attempting to remove it after using "add" instead does work though. But has not changed any of the findings in the other issues.

c:\Users\oriz1\Downloads\divi-4.0.7-win (2)>divi-cli addnode 178.62.195.16 remove
error: {“code”:-24,“message”:“Error: Node has not been added.”}

c:\Users\oriz1\Downloads\divi-4.0.7-win (2)>divi-cli addnode 178.62.195.16 onetry

c:\Users\oriz1\Downloads\divi-4.0.7-win (2)>divi-cli addnode 178.62.195.16 remove
error: {“code”:-24,“message”:“Error: Node has not been added.”}

c:\Users\oriz1\Downloads\divi-4.0.7-win (2)>divi-cli addnode 178.62.195.16 add

c:\Users\oriz1\Downloads\divi-4.0.7-win (2)>divi-cli addnode 178.62.195.16 remove

**Comment by 99darwin** [comment] 2018-08-20 19:37
#125 in vso

**Comment by oriz456** [comment] 2018-08-21 01:46
Based on Yuri's answer, it appears onetry does not add the node to the cache, which will explain why it can't remove it. Likely not a bug.

**Comment by Divicoin** [comment] 2018-08-22 02:15
Onetry establishes direct connection, without adding to cache. 

Closing as not a bug

**Closed by Divicoin** 2018-08-22 02:15 UTC
