### ISSUE TITLE
Funds sent from GUI are not valid

### ISSUE THREAD

**Issue by 99darwin** [Divicoin/Divi#50] opened 2018-07-11 02:30 UTC
# Expected behavior
Funds sent from GUI client version 1.1.23 should be valid wallet transactions visible to the blockchain
# Actual behavior
Funds sent from GUI client do not appear as valid wallet transactions and `gettransaction` returns the following error
```
error: {"code":-5,"message":"Invalid or non-wallet transaction id"}
```
# Operating system
Place an 'x' in the box next to your operating system
* [x] Mac OSX 10.13.1
* [x] Linux Ubuntu 16.04.4
* [x] Linux Ubuntu 17.04.4
* [x] Linux Ubuntu 18.04.4
* [x] Windows 10

# Steps to reproduce the problem
- Send a transaction from the GUI client
- Search [diviscan](https://diviscan.io) - returns "unable to locate transaction" error
- Search using `divi-cli gettransaction <txid>`

**Comment by Divicoin** [comment] 2018-07-20 01:05
The issue is that only counterparties can see the transaction details, and no other node on the network has access to the information.

**Comment by oriz456** [comment] 2018-07-23 15:31
Attempted to test yesterday if this is only a GUI issue or blockchain issue. Sent funds using CLI and they would still not show publicly. Thought initially that if it was merely a GUI problem, it could be related to issue #72 (just opened today). However, like I said even using CLI does not solve the issue.

**Comment by Divicoin** [comment] 2018-08-03 22:15
The correct command is `getrawtransaction <hash> 1`

Closing as not a bug.

**Closed by Divicoin** 2018-08-03 22:15 UTC
Labels: bug
