### ISSUE TITLE
UX - Receiving List of Addresses

### ISSUE THREAD

**Issue by Guritz** [Divicoin/Divi#53] opened 2018-07-11 04:37 UTC
# Expected behavior
UX - 
![addresses](https://user-images.githubusercontent.com/16604693/42550925-6e539362-8489-11e8-9076-8577312fbe92.png)
Should be able to easily see and read the text of the addresses
# Actual behavior
Depending on the running instance - shows 70 to 80 percent of text in addresses.

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [X ] Linux Ubuntu 18.04.4
* [ ] Windows 10

# Steps to reproduce the problem
Running Ubuntu 18.04 with 1.1.24 Build - this has been a consistent UX since 1.1.16

**Comment by Divicoin** [comment] 2018-07-16 18:26
Duplicate of https://github.com/Divicoin/Divi/issues/63

**Closed by Divicoin** 2018-07-16 18:26 UTC
Labels: duplicate
